/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeBreadcrumb: typeof import('primevue/breadcrumb')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeColorPicker: typeof import('primevue/colorpicker')['default']
    PrimeColumn: typeof import('primevue/column')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeDataTable: typeof import('primevue/datatable')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeDialog: typeof import('primevue/dialog')['default']
    PrimeDivider: typeof import('primevue/divider')['default']
    PrimeDrawer: typeof import('primevue/drawer')['default']
    PrimeFloatLabel: typeof import('primevue/floatlabel')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeInputGroup: typeof import('primevue/inputgroup')['default']
    PrimeInputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputMask: typeof import('primevue/inputmask')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputOtp: typeof import('primevue/inputotp')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeKnob: typeof import('primevue/knob')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeRadioButton: typeof import('primevue/radiobutton')['default']
    PrimeRating: typeof import('primevue/rating')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSkeleton: typeof import('primevue/skeleton')['default']
    PrimeTab: typeof import('primevue/tab')['default']
    PrimeTabList: typeof import('primevue/tablist')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabPanels: typeof import('primevue/tabpanels')['default']
    PrimeTabs: typeof import('primevue/tabs')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    PrimeToast: typeof import('primevue/toast')['default']
    PrimeToggleButton: typeof import('primevue/togglebutton')['default']
    PrimeToggleSwitch: typeof import('primevue/toggleswitch')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
